// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Search: typeof import('./src/components/Search/Search.vue')['default']
    SearchInput: typeof import('./src/components/Search/elements/SearchInput.vue')['default']
    SearchList: typeof import('./src/components/Search/elements/SearchList.vue')['default']
    SearchListItem: typeof import('./src/components/Search/elements/SearchListItem.vue')['default']
    SearchMatches: typeof import('./src/components/Search/SearchMatches.vue')['default']
  }
}
